Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -8,7 +8,7 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Code
-        uses: actions/checkout@v4
+        uses: actions/checkout@v4.2.2
 
       - name: Setup Build Environment
         run: |
@@ -33,7 +33,7 @@ jobs:
         run: |
           git clone --depth=1 https://github.com/osm0sis/AnyKernel3.git AK3
           
-          # Otomatis cari file Image/Image.gz/Image.gz-dtb yang ada di out/
+          # Cari otomatis file output kernel
           if [ -f out/arch/arm64/boot/Image.gz-dtb ]; then
             cp out/arch/arm64/boot/Image.gz-dtb AK3/
           elif [ -f out/arch/arm64/boot/Image.gz ]; then
@@ -41,7 +41,7 @@ jobs:
           elif [ -f out/arch/arm64/boot/Image ]; then
             cp out/arch/arm64/boot/Image AK3/
           else
-            echo "Kernel Image not found!" && exit 1
+            echo "Error: Output Kernel Image tidak ditemukan!" && exit 1
           fi
 
           cd AK3
